---

- name: add group ogn
  group: name=ogn

- name: add user ogn
  user: name=ogn group=ogn state=present
 
# NOTE: reports "changed" each time, caused by virtual packages
- name: install required packages
  apt: name={{ item }} state=present
  with_items:
  - rtl-sdr
  - libconfig-dev
  - fftw3-dev
  - libjpeg-dev
  - libconfig9

- name: download rtlsdr ogn binary
  get_url: url={{ rtlsdr_ogn_bin_url }} dest=/opt/{{ rtlsdr_ogn_bin }}
  register: ogn_download
  tags: updateogn

- name: delete old directory
  file: path=/opt/{{ item }} state=absent
  when: ogn_download.changed
  with_items:
    - rtlsdr-ogn
  tags: updateogn

- name: ...and extract it
  unarchive: src=/opt/{{ rtlsdr_ogn_bin }} dest=/opt/ creates=/opt/{{ rtlsdr_ogn_dir }} copy=no owner=root group=root
  tags: updateogn

- name: symlink directory
  file: src=/opt/{{ rtlsdr_ogn_dir }} path=/opt/rtlsdr-ogn state=link owner=root group=root
  tags: updateogn

- name: change ownership recursive
  file: path=/opt/rtlsdr-ogn/ state=directory owner=root group=root recurse=yes
  tags: updateogn

# NOTE: how to circumvent setuid?
- name: set executables permissions (setuid, setgid)
  file: path=/opt/rtlsdr-ogn/{{ item }} mode="a+s" owner=root group=root
  with_items:
    - gsm_scan
    - ogn-rf
  tags: updateogn

## NOTE: - became obsolete with 0.2.3
##       - only for RasPi I
#- name: create gpu dev node
#  command: mknod /opt/rtlsdr-ogn/gpu_dev c 100 0 creates=/opt/rtlsdr-ogn/gpu_dev
#  become: true
#  tags:
#    - debug
#    - updateogn

- name: create fifo
  command: mkfifo /opt/rtlsdr-ogn/ogn-rf.fifo creates=/opt/rtlsdr-ogn/ogn-rf.fifo
  tags: updateogn

- name: create ogn config directory
  file: path=/etc/rtlsdr-ogn state=directory owner=root group=root

- name: create ogn site config file
  template: src=site.conf.j2 dest=/etc/rtlsdr-ogn/site.conf
  tags:
    - updatesiteconf

- name: install required packages to deamonize ogn
  apt: name={{ item }} state=present
  with_items:
  - procserv
  - telnet

- name: copy ogn startup script
  copy: src=rtlsdr-ogn dest=/etc/init.d/rtlsdr-ogn owner=root group=root mode='0755'

- name: copy ogn startup config
  copy: src=rtlsdr-ogn.conf dest=/etc/rtlsdr-ogn.conf owner=root group=root mode='0644'

- name: enable ogn startupscript on boot
  service: name=rtlsdr-ogn enabled=yes state=started

- name: enable ogn startupscript on boot
  service: name=rtlsdr-ogn state=restarted
