---
# task file for rtlsdr setup

- name: install compiler environment
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - build-essential
    - git
    - cmake
    - libusb-1.0-0-dev

#- name: add git.osmocom.org host key
#  shell: /usr/bin/ssh-keyscan -H git.osmocom.org >> /etc/ssh/ssh_known_hosts

- name: clone rtl-sdr sources
  git: repo=git://git.osmocom.org/rtl-sdr.git dest=/usr/local/src/rtl-sdr accept_hostkey=yes

- name: copy rtl-sdr build script
  copy: src=build-rtl-sdr.sh dest=/usr/local/src/rtl-sdr/build-rtl-sdr owner=root group=root mode='0755'

- name: build and install rtl-sdr
  command: "/usr/local/src/rtl-sdr/build-rtl-sdr creates=/usr/local/src/rtl-sdr/build"

- name: copy rtlsdr driver blacklist
  copy: src='rtlsdr-blacklist.conf' dest='/etc/modprobe.d/rtlsdr-blacklist.conf' owner=root group=root mode='0644'
